#cargo-features = ["profile-rustflags", "trim-paths"]

[package]
name = "branch-deck"
version = "0.1.0"
description = "Branch Deck"
authors = ["you"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "branch_deck_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.6.2", features = [] }
serde = { version = "1", features = ["derive"] }
#noinspection CargoUnusedDependency
serde_json = "1"
specta = "=2.0.0-rc.22"
specta-typescript = "0.0.9"
tauri-specta = { version = "=2.0.0-rc.21", features = ["derive", "typescript"] }
tauri-plugin-store = "2"
tauri-plugin-dialog = "2"
regex = "1.11.1"
indexmap = "2.10.0"
tauri-plugin-log = "2"
git2 = {version = "0.20.2", features = ["vendored-libgit2"] }
tauri-plugin-devtools = "2.0.0"
anyhow = {version = "1.0.98", features = ["default", "backtrace"] }
similar = { version = "2.6.0", features = ["text"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt", "registry"] }
tracing-log = "0.2"
opentelemetry = "0.30.0"
opentelemetry_sdk = { version = "0.30.0", features = ["rt-tokio-current-thread"] }
opentelemetry-otlp = { version = "0.30.0", features = ["http-proto", "reqwest-blocking-client"] }
tracing-opentelemetry = "0.31.0"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }

[dev-dependencies]
tempfile = "3.20.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"
tauri-plugin-window-state = "2"

[profile.dev]
incremental = true
#rustflags = ["-Zthreads=8"]

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true # Enables link-time-optimizations.
opt-level = "z" # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort" # Higher performance by disabling panic handlers.
strip = true # Ensures debug symbols are removed.
#trim-paths = "all" # Removes potentially privileged information from your binaries.
#rustflags = ["-Cdebuginfo=0", "-Zthreads=8"] # Better compile performance.
