/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BranchCreator: typeof import('./src/components/BranchCreator.vue')['default']
    BranchPrefixHelp: typeof import('./src/components/BranchPrefixHelp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_typescript@5.8.3_vite@7.0.2_ji_9b4c8f21969cebb80341c2442b16017f/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_typescript@5.8.3_vite@7.0.2_ji_9b4c8f21969cebb80341c2442b16017f/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_typescript@5.8.3_vite@7.0.2_ji_9b4c8f21969cebb80341c2442b16017f/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_typescript@5.8.3_vite@7.0.2_ji_9b4c8f21969cebb80341c2442b16017f/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UButtonGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_typescript@5.8.3_vite@7.0.2_ji_9b4c8f21969cebb80341c2442b16017f/node_modules/@nuxt/ui/dist/runtime/components/ButtonGroup.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_typescript@5.8.3_vite@7.0.2_ji_9b4c8f21969cebb80341c2442b16017f/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UContainer: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_typescript@5.8.3_vite@7.0.2_ji_9b4c8f21969cebb80341c2442b16017f/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_typescript@5.8.3_vite@7.0.2_ji_9b4c8f21969cebb80341c2442b16017f/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_typescript@5.8.3_vite@7.0.2_ji_9b4c8f21969cebb80341c2442b16017f/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_typescript@5.8.3_vite@7.0.2_ji_9b4c8f21969cebb80341c2442b16017f/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UProgress: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_typescript@5.8.3_vite@7.0.2_ji_9b4c8f21969cebb80341c2442b16017f/node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_typescript@5.8.3_vite@7.0.2_ji_9b4c8f21969cebb80341c2442b16017f/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_typescript@5.8.3_vite@7.0.2_ji_9b4c8f21969cebb80341c2442b16017f/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
    UTree: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_typescript@5.8.3_vite@7.0.2_ji_9b4c8f21969cebb80341c2442b16017f/node_modules/@nuxt/ui/dist/runtime/components/Tree.vue')['default']
  }
}
