
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Pushes a specific branch to the remote repository
 */
async pushBranch(repositoryPath: string, branchPrefix: string, branchName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("push_branch", { repositoryPath, branchPrefix, branchName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Synchronizes branches by grouping commits by prefix and creating/updating branches
 */
async syncBranches(repositoryPath: string, branchPrefix: string, progress: TAURI_CHANNEL<SyncEvent>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_branches", { repositoryPath, branchPrefix, progress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBranchPrefixFromGitConfig(repositoryPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_branch_prefix_from_git_config", { repositoryPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkForUpdates() : Promise<Result<UpdateInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_updates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getUpdateStatus() : Promise<Result<UpdateInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_update_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installUpdate() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Branch operation errors.
 */
export type BranchError = { Generic: string } | { MergeConflict: MergeConflictInfo }
/**
 * Status of a branch synchronization operation.
 */
export type BranchSyncStatus = "Created" | "Updated" | "Unchanged" | "Error" | "MergeConflict" | "AnalyzingConflict"
/**
 * Details about a synchronized commit.
 */
export type CommitDetail = { original_hash: string; hash: string; message: string; time: number; status: CommitSyncStatus; error: BranchError | null }
/**
 * Status of a commit synchronization.
 */
export type CommitSyncStatus = "Pending" | "Created" | "Unchanged" | "Error" | "Blocked"
/**
 * Analysis results for a merge conflict, including missing commits and divergence information.
 */
export type ConflictAnalysis = { missingCommits: MissingCommit[]; mergeBaseHash: string; mergeBaseMessage: string; mergeBaseTime: number; mergeBaseAuthor: string; divergenceSummary: DivergenceSummary }
/**
 * Represents details of a conflict during a cherry-pick operation.
 * 
 * Includes the path of the conflicted file, its status, and the diff details for the conflict.
 */
export type ConflictDetail = { file: string; status: string; fileDiff: FileDiff; baseFile: FileInfo | null; targetFile: FileInfo | null; cherryFile: FileInfo | null; baseToTargetDiff: FileDiff; baseToCherryDiff: FileDiff }
/**
 * Information about a commit referenced in conflict markers
 */
export type ConflictMarkerCommitInfo = { hash: string; message: string; author: string; timestamp: number }
/**
 * Summary of how two branches have diverged from their common ancestor.
 */
export type DivergenceSummary = { commitsAheadInSource: number; commitsAheadInTarget: number; commonAncestorDistance: number }
/**
 * Represents the diff between two versions of a file.
 */
export type FileDiff = { oldFile: FileInfo; newFile: FileInfo; hunks: string[] }
/**
 * Information about a file including its content and metadata.
 */
export type FileInfo = { fileName: string; fileLang: string; content: string }
export type GroupedBranchInfo = { name: string; commits: CommitDetail[] }
/**
 * Details about a merge conflict encountered during a cherry-pick operation.
 * 
 * Contains information about the conflicting files, associated commit details, and conflict analysis results.
 */
export type MergeConflictInfo = { commitMessage: string; commitHash: string; commitTime: number; originalParentMessage: string; originalParentHash: string; originalParentTime: number; targetBranchMessage: string; targetBranchHash: string; targetBranchTime: number; conflictingFiles: ConflictDetail[]; conflictAnalysis: ConflictAnalysis; conflictMarkerCommits: Partial<{ [key in string]: ConflictMarkerCommitInfo }> }
/**
 * Represents a commit that exists in the source branch but is missing from the target branch.
 * These commits might be causing merge conflicts.
 */
export type MissingCommit = { hash: string; message: string; time: number; author: string; filesTouched: string[]; fileDiffs: FileDiff[] }
export type SyncEvent = 
/**
 * Initial progress message
 */
{ type: "Progress"; data: { message: string; index: number } } | 
/**
 * Sent immediately after grouping commits
 */
{ type: "BranchesGrouped"; data: { branches: GroupedBranchInfo[] } } | 
/**
 * Sent when a commit is successfully cherry-picked
 */
{ type: "CommitSynced"; data: { branch_name: string; commit_hash: string; new_hash: string; status: CommitSyncStatus } } | 
/**
 * Sent when a commit fails to cherry-pick
 */
{ type: "CommitError"; data: { branch_name: string; commit_hash: string; error: BranchError } } | 
/**
 * Sent to mark commits as blocked due to earlier error
 */
{ type: "CommitsBlocked"; data: { branch_name: string; blocked_commit_hashes: string[] } } | 
/**
 * Sent when a branch status changes (including during processing and completion)
 */
{ type: "BranchStatusUpdate"; data: { branch_name: string; status: BranchSyncStatus } } | 
/**
 * Final completion event
 */
{ type: "Completed" }
export type TAURI_CHANNEL<TSend> = null
export type UpdateInfo = { current_version: string; available_version: string; is_update_available: boolean; status: UpdateStatus }
export type UpdateStatus = "Idle" | "Checking" | "Downloading" | "Downloaded" | "Installing" | { Error: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
