// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateVirtualBranches(arg1) {
  return window['go']['main']['App']['CreateVirtualBranches'](arg1);
}

export function GetBranchPrefixFromGitConf(arg1) {
  return window['go']['main']['App']['GetBranchPrefixFromGitConf'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function PushBranch(arg1, arg2) {
  return window['go']['main']['App']['PushBranch'](arg1, arg2);
}
