// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CreateVirtualBranches(arg1:backend.VcsRequest):Promise<backend.ActionResult>;

export function GetBranchPrefixFromGitConf(arg1:string):Promise<backend.GlobalBranchPrefix>;

export function OpenDirectoryDialog():Promise<string>;

export function PushBranch(arg1:backend.VcsRequest,arg2:string):Promise<backend.ActionResult>;
