// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CreateVirtualBranches(arg1:string,arg2:string):Promise<backend.ProcessResult>;

export function GetRepositoryInfo(arg1:string):Promise<backend.RepositoryInfo>;

export function OpenDirectoryDialog():Promise<string>;
