// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateVirtualBranches(arg1, arg2) {
  return window['go']['main']['App']['CreateVirtualBranches'](arg1, arg2);
}

export function GetRepositoryInfo(arg1) {
  return window['go']['main']['App']['GetRepositoryInfo'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}
